import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col gap-4 p-4 w-full bg-custom-color">
          <nav>
            <ul className="flex flex-col gap-2 w-[300px]">
              <li><Link href="/nested-server-comp" className="block border border-foreground px-4 py-2 rounded hover:bg-foreground hover:text-background transition-colors">Nested Server Component</Link></li>
              <li><Link href="/middleware-test" className="block border border-foreground px-4 py-2 rounded hover:bg-foreground hover:text-background transition-colors">Middleware Test</Link></li>
              <li><Link href="/" className="block border border-foreground px-4 py-2 rounded hover:bg-foreground hover:text-background transition-colors">Home</Link></li>
            </ul>
          </nav>
        </div>
        <div className="flex flex-col gap-4 p-4 w-full bg-custom-color">
          {children}
        </div>
      </body>
    </html>
  );
}
